Kurs1/Kurs/ZLO/urls.py
"""
Definition of urls for ZLO.
"""

from datetime import datetime
from django.urls import path
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView
from app import forms, views
from django.urls import path

from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.urls import path





urlpatterns = [
    path('', views.home, name='home'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('links/', views.links, name='links'),
    path('registration/', views.registration, name='registration'),
    path('anketa/', views.anketa, name='anketa'),
    path('blog/', views.blog, name='blog'),
    path('blogpost/<int:parametr>/', views.blogpost, name='blogpost'),
    path('newpost', views.newpost, name='newpost'),
    path('videopost', views.videopost, name='videopost'),
    path('catalog/', views.catalog, name='catalog'),
    path('add_product/', views.add_product, name='add_product'),
    path('product/<int:product_id>/', views.product_detail, name='product_detail'),
    path('cart/', views.view_cart, name='cart'),
    path('product_detail/<int:product_id>/', views.product_detail, name='product_detail'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('create_order/', views.create_order, name='create_order'),
    path('accounts/login/', views.registration, name='login'),
    path('my_orders/', views.my_orders, name='my_orders'),  # Создайте отдельный вид для просмотра заказов пользователя
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/', views.view_cart, name='view_cart'),
    path('decrement_item/<int:product_id>/', views.decrement_item, name='decrement_item'),
    path('increment_item/<int:product_id>/', views.increment_item, name='increment_item'),
    path('cancel_order/<int:order_id>/', views.cancel_order, name='cancel_order'),
    path('change_order_status/<int:order_id>/', views.change_order_status, name='change_order_status'),
    

    path('all_orders/', views.all_orders, name='all_orders'),
    # Другие URL-пути
    path('login/',


         LoginView.as_view
         (
             template_name='app/login.html',
             authentication_form=forms.BootstrapAuthenticationForm,
             extra_context=
             {
                 'title': 'Авторизация',
                 'year' : datetime.now().year,
             }
         ),
         name='login'),
    path('logout/', LogoutView.as_view(next_page='/'), name='logout'),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += staticfiles_urlpatterns()

Kurs1/Kurs/app/models.py
"""
Definition of models.
"""

from django.db import models
from django.contrib import admin
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.models import User
from django.db import models
from app.cart import Cart





# Create your models here.
class Blog(models.Model):
    id = models.AutoField(primary_key=True)

   

    title = models.CharField(max_length = 100, unique_for_date = "posted", verbose_name = "Заголовок")


    description = models.TextField(verbose_name = "Краткое содержание")


    content = models.TextField(verbose_name = "Полное содержание")


    posted = models.DateTimeField(default = datetime.now(), db_index = True, verbose_name = "Опубликована")


    author = models.ForeignKey(User, null=True, blank=True, on_delete = models.SET_NULL, verbose_name = "Автор")
    
    image = models.FileField(default='temp.jpg', verbose_name = 'Путь к картинке' )
    #Методы класса:
        
    def get_absolute_url(self): # метод возвращает строку с URL-адресом записи
        return reverse("blogpost", args [str(self.id)])

    def __str__(self): # метод возвращает название, используемое для представления отдельных записей в административном разделе
        return self.title
        #Метаданные - вложенный класс, который задает дополнительные параметры модели:
    class Meta:
        db_table = "Posts" # имя таблицы для модели
        ordering = ["-posted"] # порядок сортировки данных в нодели (*-* означает по убыванию)
        verbose_name = "статья блога" # имя, под которым модель будет отображаться в административном разделе (для одной статья блог
        verbose_name_plural = "статьи блога" # то не для всех статей блога
        
admin.site.register(Blog)


class Comment(models.Model):
    text = models.TextField(verbose_name = "Текст комментария")
    date = models.DateTimeField(default = datetime.now(), db_index = True, verbose_name = "Дата комментария")
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name = "Статья удалена")
    post = models.ForeignKey(Blog, on_delete = models.CASCADE, verbose_name = "Статья комментария")
    id = models.BigAutoField(primary_key=True)
    #Методы класса
    def str(self):
        return 'Комментарий %d %s к %s' % (self.id, self.author, self.post)
    class Meta:
        db_table = "Comment"
        ordering = ["-date"]
        verbose_name = "Комментарий к статье блога"
        verbose_name_plural = "Комментарии к статьям блога"
admin.site.register(Comment)




class Category(models.Model):
    name = models.CharField(max_length=255)
    id = models.BigAutoField(primary_key=True)



class Product(models.Model):
    # Ваши поля для товара
    name = models.CharField(max_length=255)
    description = models.TextField()
    price = models.DecimalField(max_digits=10, decimal_places=2)
    image = models.ImageField(upload_to='products/', blank=True, null=True)
    category = models.TextField()
    discount = models.DecimalField(max_digits=5, decimal_places=2, verbose_name="Скидка", default=0, null=True, blank=True)
    id = models.BigAutoField(primary_key=True)
     # Первое изображение
    image = models.ImageField(upload_to='product_images/', blank=True, null=True)
    # Дополнительные изображения
    additional_images = models.ManyToManyField('ProductImage', blank=True, related_name='product')

    
    floors = models.IntegerField(verbose_name="Этажи", default=None, null=True)
    area = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Площадь", default=0, null=True)
    
    materials = models.CharField(max_length=255, verbose_name="Материалы", default='', null=True)

    def __str__(self):
        return self.name
admin.site.register(Product)


class ProductImage(models.Model):
    image = models.ImageField(upload_to='products', default='no_image.png')
class Cart(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    products = models.ManyToManyField('Product', through='CartItem')
    id = models.BigAutoField(primary_key=True)


class CartItem(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    id = models.BigAutoField(primary_key=True)

class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    created_at = models.DateTimeField(auto_now_add=True)
    items = models.ManyToManyField('Product', through='OrderItem')
    id = models.BigAutoField(primary_key=True)
    STATUS_CHOICES = (
        ('created', 'Заказ создан'),
        ('ready', 'Готов к выдаче'),
        ('canceled', 'Отменен'),
    )
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='created')
    address = models.CharField(max_length=255, default='')
    name = models.CharField(max_length=255, default='')
    email = models.EmailField(default='')
    phone_number = models.CharField(max_length=20, default='')

    def __str__(self):
        return f'Order {self.id} - {self.status}'
admin.site.register(Order)
    # Добавьте другие поля, которые вам нужны для заказа

 


class OrderItem(models.Model):  # Добавим определение OrderItem
    order = models.ForeignKey('Order', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    id = models.BigAutoField(primary_key=True)

Kurs1/Kurs/app/templates/app/about.html
{% extends "app/layout.html" %}
{% load static %}

{% block content %}

<div class="container about-us">
    <div class="row">
        <div class="col-md-8 bordered-block">
            <h3>Псковский центр деревянных строений</h3>
            <p>
                На строительном рынке Пскова наша компания работает с 2007 г.
                Делаем фундаменты, монтируем срубы, облицовываем,
                благоустраиваем дома под ключ! Также специализируемся
                на проектировании и строительстве каркасных домов,
                домов из профилированного бруса, каркасных бань, бань из
                профилированного бруса, беседок и хоз. блоков.
            <p>
                Индивидуальный подход к каждому клиенту.
                Также можете заказать товар на вывоз,
                с доставкой до дома, по телефону или по электронной почте,
                или сделать заявку на сайте.
            </p>
        </div>
        <div class="col-md-4 bordered-block">
            <h3>Почему мы?</h3>
            <ul class="list-group">
                <li class="list-group-item">Профессиональное качество</li>
                <li class="list-group-item">Быстрые сроки</li>
                <li class="list-group-item">Доставка по Пскову</li>
                <li class="list-group-item">Доставка по России</li>
                <li class="list-group-item">Сезонные скидки</li>
            </ul>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <h2>Также мы занимаемся</h2>
            <p>
                Наша компания занимается проектированием и строительством каркасных домов, домов из профилированного бруса, каркасных бань, бань из
                профилированного бруса, беседок и хоз. блоков.
            </p>
            <p>
                Индивидуальный подход к каждому клиенту. Также можете заказать товар на вывоз, с доставкой до дома, по телефону или по электронной почте,
                или сделать заявку на сайте.
            </p>
        </div>
    </div>

    <div class="row team">
        <div class="col-md-3">
            <div class="card">
                <img src="{% static 'app/content/павел.jpg' %}" alt="Павел Николаевич" class="card-img-top">
                <div class="card-body">
                    <h4 class="card-title">Павел Николаевич</h4>
                    <p class="card-text">Директор</p>
                    <p class="card-text">Всегда в хорошем расположении духа, очень активен и внимателен.</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <img src="{% static 'app/content/мария.jpg' %}" alt="Мария Николаевна" class="card-img-top">
                <div class="card-body">
                    <h4 class="card-title">Мария Николаевна</h4>
                    <p class="card-text">Менеджер</p>
                    <p class="card-text">С радостью ответит на все ваши вопросы.</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <img src="{% static 'app/content/сергей.jpg' %}" alt="Сергей Петрович" class="card-img-top">
                <div class="card-body">
                    <h4 class="card-title">Сергей Петрович</h4>
                    <p class="card-text">Инженер-проектировщик</p>
                    <p class="card-text">Поможет сделать ваш индивидуальный проект.</p>
                </div>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card">
                <img src="{% static 'app/content/виктор.jpg' %}" alt="Виктор Анатольевич" class="card-img-top">
                <div class="card-body">
                    <h4 class="card-title">Виктор Анатольевич</h4>
                    <p class="card-text">Мастер</p>
                    <p class="card-text">Под его руководством ваш проект обретет жизнь.</p>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <p>
                По желанию заказчика ведем монтаж фундамента, монтируем срубы, облицовываем, благоустраиваем дома, бани, хозблоки.
            </p>
        </div>
    </div>

</div>


{% endblock %}

Kurs1/Kurs/app/templates/app/all_orders.html
{% extends "app/layout.html" %}
{% block content %}


<h2>Все заказы</h2>

    {% if orders %}

            {% for order in orders %}
<div class="order">
    <h3>Заказ №{{ order.id }}</h3>
    <div class="order-info">
        <p>Пользователь: {{ order.user.username }}</p>
        <p>Дата создания: {{ order.created_at }}</p>
        <p>Статус: {{ order.get_status_display }}</p>
        <p>Адрес: {{ order.address }}</p>
        <p>Имя: {{ order.name }}</p>
        <p>Почта: {{ order.email }}</p>
        <p>Номер телефона: {{ order.phone_number }}</p>
    </div>

    <h4>Товары в заказе:</h4>

    
    <p>
        
        <div class="order-items">
            {% for item in order.orderitem_set.all %}
            <p>
                {{ item.product.name }} - {{ item.quantity }} шт.
                {% if item.product.discount > 0 %}
                Цена со скидкой: <span class="discount-price">{{ item.discounted_price|floatformat:2 }}</span> (скидка {{ item.product.discount|floatformat:0 }}%)
                Старая цена: {{ item.product.price }}
                {% else %}
                Цена: {{ item.product.price }}
                {% endif %}

            </p>
            {% endfor %}
        </div>

        <div class="order-total">
            Итоговая стоимость: {{ order.total_price }}
        </div>

        <form method="post" action="{% url 'change_order_status' order.id %}">
            {% csrf_token %}
            <div class="form-group">
                <select name="status" class="form-control">
                    {% for choice in order.STATUS_CHOICES %}
                    <option value="{{ choice.0 }}" {% if choice.0 == order.status %}selected{% endif %}>
                        {{ choice.1 }}
                    </option>
                    {% endfor %}
                </select>
            </div>
            <button type="submit" class="btn btn-primary">Изменить статус</button>
        </form>
</div>
            {% endfor %}

    {% else %}
<p>Пока нет заказов.</p>
    {% endif %}


{% endblock %}

Kurs1/Kurs/app/templates/app/anketa.html
{% extends "app/layout.html" %}
{% block content %}
{% if form != None %}


<br>
<h2>Отправте пожалуйста отзыв о сайте</h2>
<br>
<div>
    <form method="post">
        {% csrf_token %}
        <label for="{{form.name.id_for_label}}">{{form.name.label}}:</label>
        {{form.name}}<br><br>
        <label for="{{form.city.id_for_label}}">{{form.city.label}}:</label>
        {{form.city}}<br><br>
        <label for="{{form.gender.id_for_label}}">{{form.gender.label}}:</label>
        {{form.gender}}<br><br>
        <label for="{{form.disain.id_for_label}}">{{form.disain.label}}:</label>
        {{form.disain}}<br><br>
        <label for="{{form.tehnik.id_for_label}}">{{form.tehnik.label}}:</label>
        {{form.tehnik}}<br><br>
        <label for="{{form.email.id_for_label}}">{{form.email.label}}:</label>
        {{form.email}}<br><br>
        <label for="{{form.notice.id_for_label}}">{{form.notice.label}}:</label>
        {{form.notice}}<br><br>
        <label for="{{form.polza.id_for_label}}">{{form.polza.label}}:</label>
        {{form.polza}}<br><br>
        <label for="{{form.nedostatki.id_for_label}}">{{form.nedostatki.label}}:</label>
        {{form.nedostatki}}<br><br>
        <input type="submit" value="Отправить" id="sub">

    </form>

</div>
<script>
    const elem = document.getElementById('sub');
    elem.addEventListener('mouseover', function () {
        elem.style.color = 'orange';

    });
    elem.addEventListener('mouseout', function () {
        elem.style.color = 'green'
    });

    const elem2 = document.getElementById('id_name');
    elem2.addEventListener('mouseover', function () {
        elem2.style.backgroundColor = 'orange';

    });
    elem2.addEventListener('mouseout', function () {
        elem2.style.backgroundColor = 'green'
    });
    const elem3 = document.getElementById('id_city');
    elem3.addEventListener('mouseover', function () {
        elem3.style.backgroundColor = 'orange';

    });
    elem3.addEventListener('mouseout', function () {
        elem3.style.backgroundColor = 'green'
    });
    const elem4 = document.getElementById('id_disain');
    elem4.addEventListener('mouseover', function () {
        elem4.style.backgroundColor = 'orange';

    });
    elem4.addEventListener('mouseout', function () {
        elem4.style.backgroundColor = 'green'
    });
</script>
{% else %}

<br>
<h2>Благодарим за предоставленную информацию!</h2>
<h3>Вы сообщили следущее:</h3>
<ul>
    <li><span>Имя:</span>{{data.name}}</li>
    <li><span>Город:</span>{{data.city}}</li>
    <li><span>Пол:</span>{{data.gender}}</li>
    <li><span>Дизан:</span>{{data.disain}}</li>
    <li><span>Польза:</span>{{data.polza}}</li>
    <li><span>Недостатки:</span>{{data.nedostatki}}</li>
    <li><span>email:</span>{{data.tehnik}}</li>
    <li><span>Рассылка:</span>{{data.notice}}</li>



</ul>
{% endif %}
{% endblock %}

Kurs1/Kurs/app/templates/app/blog.html
{% extends "app/layout.html" %}

{% block content %}
{% block head %}
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'app/content/styles.css' %}" />
{% endblock %}
<div class="blog-container">
    <h2 class="blog-title">{{ title }}</h2>
    <br />

    {% for post in posts %}
    <div class="blog-post">
        <h2 class="blog-title">{{ post.title }}</h2>
        <h4 class="posted-info">{{ post.posted }}</h4>
        <p class="blog-description">{{ post.description }}</p>
        <p><a href="{% url 'blogpost' parametr=post.id %}" class="read-more-link">Читать далее</a></p>
    </div>
    {% endfor %}
</div>
{% endblock %}

Kurs1/Kurs/app/templates/app/cart.html
{% extends "app/layout.html" %}

{% block head %}
    {% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.min.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'app/content/bootstrap.css' %}" />
<link rel="stylesheet" type="text/css" href="{% static 'app/content/styles.css' %}" />
{% endblock %}

{% block content %}
<div class="cart-container">
    <h1>Ваша корзина</h1>

    {% for item in cart %}
    <div class="cart-item">
        <img src="{{ item.product.image.url }}" alt="{{ item.product.name }}" class="cart-item-image">
        <div class="cart-item-details">
            <p class="cart-item-name">{{ item.product.name }}</p>
            <p>Количество: {{ item.quantity }}</p>
            <p>
                {% if item.product.discount > 0 %}
                Цена со скидкой: {{ item.price }} (скидка {{ item.product.discount|floatformat:0 }}%)
                Старая цена: {{ item.product.price }}
                {% else %}
                Цена: {{ item.price }}
                {% endif %}
            </p>
        </div>
        <div class="cart-item-actions">
            <a href="{% url 'remove_from_cart' item.product.id %}" class="cart-action-link">Удалить</a>
            <a href="{% url 'decrement_item' item.product.id %}" class="cart-action-link">Уменьшить</a>
            <a href="{% url 'increment_item' item.product.id %}" class="cart-action-link">Увеличить</a>
        </div>
    </div>
    {% endfor %}

    <p class="cart-summary">Итого товаров в корзине: {{ cart|length }}</p>
    <p class="cart-summary">Общая стоимость: {{ cart.get_total_price }}</p>
</div>
<button type="button" class="btn btn-primary" id="checkoutBtn">
    Оформить заказ
</button>

<!-- Модальное окно для оформления заказа -->
<div class="modal" id="orderModal" tabindex="-1" role="dialog" aria-labelledby="orderModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="orderModalLabel">Оформление заказа</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <!-- Сообщение об ошибке -->
                <div id="error-message" style="color: red; display: none;">Нет товара в корзине.</div>
                <!-- Сообщение об ошибке валидации формы -->
                <div id="form-error-message" style="color: red; display: none;"></div>
                <!-- Форма оформления заказа -->
                <form method="post" action="{% url 'create_order' %}" id="orderForm">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="address">Адрес:</label>
                        <input type="text" class="form-control" id="address" name="address" required>
                    </div>
                    <div class="form-group">
                        <label for="name">Имя:</label>
                        <input type="text" class="form-control" id="name" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="email">Почта:</label>
                        <input type="email" class="form-control" id="email" name="email" required>
                    </div>
                    <div class="form-group">
                        <label for="phone_number">Номер телефона:</label>
                        <input type="tel" class="form-control" id="phone_number" name="phone_number" required>
                    </div>
                    <button type="submit" class="btn btn-primary">Оформить</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
<script>
    // Получаем элементы
    const checkoutBtn = document.getElementById('checkoutBtn');
    const orderModal = document.getElementById('orderModal');
    const errorMessage = document.getElementById('error-message');
    const formErrorMessage = document.getElementById('form-error-message');
    const closeBtn = document.querySelector('.close');
    const orderForm = document.getElementById('orderForm');
    const addressInput = document.getElementById('address');
    const phoneNumberInput = document.getElementById('phone_number');

    // Добавляем обработчик события клика на кнопку "Оформить заказ"
    checkoutBtn.addEventListener('click', function (event) {
        event.preventDefault();  // Предотвращаем переход по ссылке
        if ({{ cart|length }} === 0) {
            errorMessage.style.display = 'block';  // Показываем сообщение об ошибке
        } else {
            errorMessage.style.display = 'none';  // Скрываем сообщение об ошибке
            orderModal.style.display = 'block';  // Показываем модальное окно
        }
    });

    // Добавляем обработчик события клика на кнопку закрытия
    closeBtn.addEventListener('click', function () {
        orderModal.style.display = 'none';  // Скрываем модальное окно
    });

    // Добавляем обработчик события клика вне модального окна
    window.onclick = function (event) {
        if (event.target === orderModal) {
            orderModal.style.display = 'none';  // Скрываем модальное окно
        }
    }

    // Добавляем обработчик события отправки формы
    orderForm.addEventListener('submit', function(event) {
        const cartLength = {{ cart|length }};
        const address = addressInput.value;
        const phoneNumber = phoneNumberInput.value;

        let valid = true;
        let errorMessageText = '';

        if (cartLength === 0) {
            valid = false;
            errorMessageText = 'Нет товара в корзине.';
        }

        if (address.length < 5) {
            valid = false;
            errorMessageText += '<br>Адрес должен содержать минимум 5 символов.';
        }

        if (!/^\d{11}$/.test(phoneNumber)) {
            valid = false;
            errorMessageText += '<br>Номер телефона должен содержать ровно 11 цифр и не должен содержать букв.';
        }

        if (!valid) {
            event.preventDefault();  // Предотвращаем отправку формы
            formErrorMessage.innerHTML = errorMessageText;
            formErrorMessage.style.display = 'block';  // Показываем сообщение об ошибке
        } else {
            formErrorMessage.style.display = 'none';  // Скрываем сообщение об ошибке
        }
    });
</script>
{% endblock %}

Kurs1/Kurs/app/templates/app/catalog.html
{% extends "app/layout.html" %}



{% block content %}
<div class="product-catalog">
    <h2>Каталог товаров</h2>

    <label for="price-filter-min">Цена от:</label>
    <input type="number" id="price-filter-min" onchange="filterByPrice()" class="price-input"><br>

    <label for="price-filter-max">Цена до:</label>
    <input type="number" id="price-filter-max" onchange="filterByPrice()" class="price-input">
    <form method="get" action="{% url 'catalog' %}" class="search-form">
        <input type="text" name="q" placeholder="Поиск по названию..." class="form-control">
        <button type="submit" class="btn btn-primary">Поиск</button>
    </form>
    <label for="category-filter">Фильтр по категории:</label>
    <select id="category-filter" onchange="filterByCategory(this.value)">
        <option value="">Все категории</option>
        {% for category in categories %}
        <option value="{{ category }}">{{ category }}</option>
        {% endfor %}

    </select>

    <div class="product-list">
        {% for product in products %}
        <div class="product-item" data-category="{{ product.category }}">

            <div class="product-info">
                <a href="{% url 'product_detail' product.id %}" class="product-name">{{ product.name }}</a>
                <a href="{% url 'product_detail' product.id %}" class="product-image-link">
                    <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image" />
                </a>
                {% if product.discount > 0 %}
                <span class="discount-label">-{{ product.discount|floatformat:0 }}%</span>
                Цена со скидкой: <span class="price-value">{{ product.discounted_price|floatformat:2 }}</span>
                Старая цена: {{ product.price }}
                {% else %}
                Цена: <span class="price-value">{{ product.price }}</span>
                {% endif %}


                <p class="cart-info">Товаров в корзине: <span id="cart-items-count-{{ product.id }}">{{ product.cart_quantity }}</span></p>
                <p class="product-price">Категория: {{ product.category }}</p>
                <form method="post" action="{% url 'add_to_cart' product.id %}" class="add-to-cart-form">
                    {% csrf_token %}
                    <button class="add-to-cart-btn" data-product-id="{{ product.id }}">Добавить в корзину</button>
                </form>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

<script>
    function filterByCategory(category) {
        const items = document.querySelectorAll('.product-item');
        items.forEach(item => {
            if ((!category || item.dataset.category === category) && isPriceInRange(item)) {
                item.style.display = 'block';
            } else {
                item.style.display = 'none';
            }
        });
    }

    function isPriceInRange(item) {
        const minPrice = document.getElementById('price-filter-min').value;
        const maxPrice = document.getElementById('price-filter-max').value;
        const priceElement = item.querySelector('.price-value');
        const price = parseFloat(priceElement.textContent);
        return (!minPrice || price >= minPrice) && (!maxPrice || price <= maxPrice);
    }

    function filterByPrice() {
        const minPrice = document.getElementById('price-filter-min').value;
        const maxPrice = document.getElementById('price-filter-max').value;
        const items = document.querySelectorAll('.product-item');

        items.forEach(item => {
            const priceElement = item.querySelector('.price-value');
            const price = parseFloat(priceElement.textContent);
            if ((!minPrice || price >= minPrice) && (!maxPrice || price <= maxPrice)) {
                item.style.display = 'block';
            } else {
                item.style.display = 'none';
            }
        });
    }
    window.addEventListener('load', function () {
        const productItems = document.querySelectorAll('.product-item');

        if (productItems.length === 1) {
            productItems[0].classList.add('single-product');
        }
    });
</script>

{% endblock %}

Kurs1/Kurs/app/templates/app/links.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>


{% load static%}
<div>
    <p><b>dns</b><a href="https://www.dns-shop.ru/" target="_blank"> <img src="{% static 'app/content/icond.png' %}" alt="Logo 1" /></a></p>
    <p><b>mvideo</b><a href="https://www.mvideo.ru" target="_blank"> <img src="{% static 'app/content/iconm.png' %}" alt="Logo 2" /></a></p>
    <p><b>ozon</b><a href="https://www.ozon.ru/category/bytovaya-tehnika-10500/" target="_blank"> <img src="{% static 'app/content/icona.png' %}" alt="Logo 3" /></a></p>
</div>

{% endblock %}

Kurs1/Kurs/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout/" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><span class="navbar-brand">привет {{ user.username }}</span></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Выйти</a></li>
    </ul>
</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Авторизация</a></li>
</ul>

{% endif %}

Kurs1/Kurs/app/templates/app/multi_image_upload.html
<div class="multi-image-upload">
    {{ widget.input_type }}
    {{ widget.name }}
    <div class="uploaded-images">
        {% for image in widget.value.all %}
            <img src="{{ image.url }}" alt="">
        {% endfor %}
    </div>
</div>

Kurs1/Kurs/app/templates/app/newpost.html
{% extends "app/layout.html" %}
{% block content %}

<div class="blog-form-container">
    <h3>Добавить статью</h3>
    <form method="POST" enctype="multipart/form-data" class="blog-form">
        {% csrf_token %}
        <div>
            {{ blogform.as_p }}
            <button type="submit" class="save btn btn-default">Сохранить статью</button>
        </div>
    </form>
</div>

{% endblock %}